<option value="AmericanExpress">American Express</option>
<option value="DinersClub">Diners Club</option>
<option value="Discover">Discover</option>
<option value="EnRoute">EnRoute</option>
<option value="JCB">JCB</option>
<option value="MasterCard">Master Card</option>
<option value="Solo">Solo</option>
<option value="Switch">Switch</option>
<option value="Visa">Visa</option>
<option value="VisaElectron">Visa Electron</option>
